[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self'; object-src 'none'; base-uri 'self'; frame-src 'none';"
    X-XSS-Protection = "1; mode=block"
