[build]
  publish = "public"

[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google-analytics.com https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://*.doubleclick.net https://tpc.googlesyndication.com https://www.googleadservices.com https://www.google.com; connect-src 'self' https://www.google-analytics.com https://www.google.com/ccm/collect https://googleads.g.doubleclick.net https://www.googleadservices.com https://stats.g.doubleclick.net; font-src 'self' https://fonts.gstatic.com; frame-src 'self' https://www.youtube.com; child-src 'self' https://www.youtube.com; manifest-src 'self'; worker-src 'self' blob:; object-src 'none'"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
