[build]
  publish = "public"

[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """default-src 'self';
      script-src 'self' https://www.googletagmanager.com https://googleads.g.doubleclick.net https://www.googleadservices.com https://pagead2.googlesyndication.com;
      connect-src 'self' https://www.google-analytics.com https://www.google.com/ccm/collect https://googleads.g.doubleclick.net https://www.googleadservices.com https://stats.g.doubleclick.net;
      frame-src 'self' https://www.googletagmanager.com https://td.doubleclick.net https://googleads.g.doubleclick.net https://tpc.googlesyndication.com;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https://*.doubleclick.net https://tpc.googlesyndication.com;
      font-src 'self';
      object-src 'none';
      base-uri 'self';
      form-action 'self';"""
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
