# Netlify Configuration (netlify.toml)

[build]
  publish = "build"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google-analytics.com https://www.googletagmanager.com https://www.googleadservices.com https://www.doubleclick.net;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https://www.google.com https://www.youtube.com;
      font-src 'self';
      connect-src 'self' https://www.google-analytics.com https://www.googletagmanager.com https://www.googleadservices.com https://stats.g.doubleclick.net;
      frame-src 'self' https://www.youtube.com https://www.google.com;
      frame-ancestors 'self';
      upgrade-insecure-requests;
      block-all-mixed-content;
    """
